### ISSUE TITLE
Module not found: Error: Can't resolve 'ng2-cache/ng2-cache'

### ISSUE THREAD

**Issue by marthakdk** [Jackson88/ng2-cache#13]
Hello All,
I am creating a custom module which contains some functionalities of centralization something that is used throughout multiple angular apps. 

I am publishing this module locally including ng2-cache module.

Problem Statement: When i use ng2-cache module inside my module (i.e Core Module) and once i use this Core Module inside another app and compile, compiler throws following error

ERROR in ../app-core/dist/src/core/services/remote.service.js
Module not found: Error: Can't resolve 'ng2-cache/ng2-cache' in 'C:\Dhaval\app-core\dist\src\core\services'
 @ ../app-core/dist/src/core/services/remote.service.js 13:18-48
 @ ../app-core/dist/src/app.core.js
 @ ./src/app-features/services/authentication/authentication.service.ts
 @ ./src/app-features/app-features.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

Is it because i am importing custom module inside my on going custom module?

**Comment by paritosh64ce** [comment]
I think this issue is similar to #21 
Try to have this ` include section` inside `tsconfig.json` of your Core module.

    "include": [
      "src/**/*",
      "node_modules/ng2-cache/ng2-cache.ts"
    ]

And then try to import you Core module in the another app.
Let me know if this fix you issue.

**Comment by paritosh64ce** [comment]
Your `ng2-cache` might have not bundled along with your Core Module.
Try using `ng2-cache` as a dependency of your 'another app' (consumer app of your Core Module) and check.
Don't forget to mention it inside `tsconfig.json` file!
