### ISSUE TITLE
Angular AOT/ngc support

### ISSUE THREAD

**Issue by MrLuje** [Jackson88/ng2-cache#15]
ng2-cache does not ship with *.metadata.json files next to the *.d.ts files. 
This is needed for AoT compiled apps [(reference)](https://github.com/angular/angular/issues/11262#issuecomment-244472000)

For now, I got the following error while ngc :

```
ngc -p tsconfig.ngc.json

Error: ENOENT: no such file or directory, open 'E:\tfswork\3\s\dist\module\node_modules\ng2-cache\src\interfaces\cache-options.interface.metadata.json'
```

Can you please check ?

**Comment by Nikhilkapoor20** [comment]
Any update on AOT support?

**Comment by marioteik** [comment]
+1

**Comment by wilmarques** [comment]
Any news about this?

**Comment by paritosh64ce** [comment]
Could you close this issue if its fixed with this PR and the updated npm package (v 0.2.0)?

**Comment by MrLuje** [comment]
Different issue now : 

_ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-cache' in '\test-ng2-cache\src\app'_

I suppose it may comes from ng2-cache's packages.json: main/module/es2015 points to missing files in published package

![image](https://user-images.githubusercontent.com/632075/39965598-73f726a0-569c-11e8-8621-50b13b48fac7.png)

**Comment by paritosh64ce** [comment]
Yes, I am able to reproduce this issue. Seems like the published package is not having the `bundles`, `esm5` and `esm2015` folders.

When I try building the package from the source code with `npm run publish:lib` command, I can see the required files/folders present in the `dist` for me.   
Seems like the package is not published with this command.

@Jackson88  - I tried publishing the package myself, however, I guess I am not having the permission. Could you publish the package using `npm run publish:lib`  command? It's present in the `package.json -> script` block. This is important as the required folders/files (as per Angular Package Format) will be generated only when we build/publish with these commands.

 *PS: We'll need to update the version in package.json file*

**Comment by paritosh64ce** [comment]
ng2-cache@0.2.1 is published. This issue is fixed along with it. You may close this issue.
