### ISSUE TITLE
Add support of Angular 5

### ISSUE THREAD

**Issue by khoden** [Jackson88/ng2-cache#16]
Angular 5 uses TypeScript 2.4.2.

Now compiler fails with error:
```
ERROR in ./node_modules/ng2-cache/src/services/cache.service.ts
Module build failed: Error: /work/st-cloud-one-five-zero/node_modules/ng2-cache/src/services/cache.service.ts is not part of the compilation output. Please check the other error messages for details.
```

To workaround this I have to add

```
"include": [
    "src/**/*",
    "node_modules/ng2-cache/src/**/*"
  ]
```

into my `tsconfig.json`.

Please fix error or add workaround to README.md

**Comment by khoden** [comment]
If import from `ng2-cache` (not from `ng2-cache/src/services/cache.service.ts`), the error disappears.

**Comment by khoden** [comment]
Workaround with include section in `tsconfig.json` not works for karma-tests (Angular-CLI project), even if I import from `ng2-cache` or `ng2-cache/ng2-cache`.

**Comment by nischi** [comment]
Please add support.

**Comment by misaizdaleka** [comment]
+1

**Comment by misaizdaleka** [comment]
These fixes are not working for me.

**Comment by rubenkuipers** [comment]
+1

**Comment by rubenkuipers** [comment]
These fixes aren't working for me either

**Comment by tlukka** [comment]
+ 1 I am able facing same issue. but added as include for work around

**Comment by paritosh64ce** [comment]
> Workaround with include section in tsconfig.json not works for karma-tests (Angular-CLI project), even if I import from ng2-cache or ng2-cache/ng2-cache.

@KhodeN - for karma-tests, you have to mention reference to `ng2-cache/ng2-cache` inside `tsconfig.spec.json` file.

**Comment by paritosh64ce** [comment]
Could you close this issue if its fixed with this PR and the updated npm package (v 0.2.0)?

**Comment by khoden** [comment]
It doesn't work for project started from @angular/cli@1.74 (based on angular 5.2).

```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-cache' in '/private/tmp/ng2-cache-bug/src/app'
```

Same error is for angular 6.0.

Why I have to add anything to my tsconfig? Any other library doesn't need that action.

`app.module.ts`
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { Ng2CacheModule } from 'ng2-cache';

import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    Ng2CacheModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by paritosh64ce** [comment]
@KhodeN  - I agree, the PR #25  to fix this issue has been already accepted. However, the latest published package (v2.0.0) on npm has some issue, I have requested @Jackson88  to republish it. Check [this comment](https://github.com/Jackson88/ng2-cache/issues/15#issuecomment-388641003) for reference.

Once it gets published, you will not see this issue.

**Comment by paritosh64ce** [comment]
ng2-cache@0.2.1 is published. This issue is fixed along with it. You may close this issue.

No need to mentioned the reference in tsconfig.json now.

**Comment by khoden** [comment]
Big thanks!
