### ISSUE TITLE
Update for the doc

### ISSUE THREAD

**Issue by amir-zahedi** [Jackson88/ng2-cache#3]
Works perfectly for me but the doc is out of date for switching to local storage on angular 2.0.
This will work with angular 2.0:
providers: [
    CacheService,
    {provide: CacheStorageAbstract,  useClass:CacheLocalStorage }
]
Cheers

**Comment by Jackson88** [comment]
Thank you for your feedback again :) Will check

**Comment by Jackson88** [comment]
Fixed, thanks again
