### ISSUE TITLE
Module has no exported member 'provide'

### ISSUE THREAD

**Issue by ronilitman** [Jackson88/ng2-cache#4]
Hi,

I want to use this module with local storage and not the default session storage, when I follow the instructions on the readme file - provide(CacheStorageAbstract, { useClass: CacheLocalStorage }) I get an error - "Module has no exported member 'provide'.

Is there something that i miss?

Thanks

**Comment by Jackson88** [comment]
Hi, 
Thanks for issue, I've fixed 'readme', correct way is:
`providers: [
        {provide: CacheStorageAbstract, useClass:CacheLocalStorage}
  ]`
Previous variant was for old versions on A2
