### ISSUE TITLE
Add support of Angular 4

### ISSUE THREAD

**Issue by brentos99** [Jackson88/ng2-cache#8]
Would like to use this module with the recently released Angular 4.0.0.

**Comment by ipoweb** [comment]
Please add support for Angular 4.0.0 💃

**Comment by Jackson88** [comment]
Added in 0.1.9, thanks for your comments :)

**Comment by chuckmah** [comment]
can you make it ^4.0.0 to make it work without warning when npm install along side with angular-cli ?

**Comment by jcwrightson** [comment]
Doesn't seem to work in ng4... returns a 404...

**Comment by Jackson88** [comment]
@chocmah thank you for your comment, changed
