### ISSUE TITLE
error TS7017: Index signature of object type implicitly has an 'any' type.

### ISSUE THREAD

**Issue by Muldoser** [Jackson88/ng2-cache#9]
`node_modules/ng2-cache/src/services/cache.service.ts(111,21): error TS7017: Index signature of object type implicitly has an 'any' type.`

This blocks our production build every time. I resolve it by explicitly adding `: any` and `as any` to line 106 of the cache.service.ts file. The `as any` is not necessary. It looks like this:

``` javascript 
...
public getTagData(tag: string) {
        let tags = this.get(this._tagsStorageKey()) || {},
            result: any = {} as any;
        if (tags[tag]) {
...
```

It's a bit inefficient as I have to apply this change every time I do an npm install or yarn.

**Comment by Jackson88** [comment]
Hi, thank you for PR! merged and fixed )
